server:
  port: 10002

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  
spring:
  security:
   basic:
     enabled: true
   user:
     name: kido
     password: kidomicroservice